
build:
	docker build -t quay.io/incendonet/centos7-sbbin_nospeech -f Dockerfile .
	docker tag quay.io/incendonet/centos7-sbbin_nospeech:latest quay.io/incendonet/centos7-sbbin_nospeech:7.0.0.0
	docker tag quay.io/incendonet/centos7-sbbin_nospeech:latest localhost:5000/centos7-sbbin_nospeech