#
# Makefile
#
# $Id: //poco/1.4/Foundation/samples/SBLauncher/Makefile#1 $
#
# Makefile for Poco SBLauncher
#

POCO_BASE = /usr/local/src/poco-1.7.8p3

include $(POCO_BASE)/build/rules/global

objects = SBLauncher ALTManager AudiortrLauncherThread

target         = SBLauncher
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
